name: Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build
        env:
          VITE_RESOURCE_URL: ${{ vars.RESOURCE_URL }}
          VITE_HELOG_EDITOR_URL: ${{ vars.HELOG_EDITOR_URL }}
          VITE_HELOG_ACCOUNT_URL: ${{ vars.HELOG_ACCOUNT_URL }}
      
      - name: Deploy production to cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
